export const emailHistoryDummy = [
  {
    title: "Welcome Email",
    subject: "Welcome to Our Platform",
    message: "Hello, thank you for joining us! We're excited to have you here.",
    sender: "no-reply@ourplatform.com",
    recipient: "user1@example.com",
    timestamp: "2024-12-20T10:00:00Z",
  },
  {
    title: "Weekly Newsletter",
    subject: "Your Weekly Update",
    message: "Here's the latest news and updates from our platform.",
    sender: "newsletter@ourplatform.com",
    recipient: "user2@example.com",
    timestamp: "2024-12-20T10:05:00Z",
  },
  {
    title: "Password Reset",
    subject: "Password Reset Request",
    message:
      "We received a request to reset your password. Click the link below to proceed.",
    sender: "support@ourplatform.com",
    recipient: "user3@example.com",
    timestamp: "2024-12-20T10:10:00Z",
  },
  {
    title: "Feedback Request",
    subject: "We Value Your Feedback",
    message:
      "We'd love to hear your thoughts about our platform. Please take a moment to fill out our survey.",
    sender: "feedback@ourplatform.com",
    recipient: "user4@example.com",
    timestamp: "2024-12-20T10:15:00Z",
  },
  {
    title: "Account Verification",
    subject: "Verify Your Account",
    message: "Please verify your account by clicking the link below.",
    sender: "no-reply@ourplatform.com",
    recipient: "user5@example.com",
    timestamp: "2024-12-20T10:20:00Z",
  },
  {
    title: "Subscription Confirmation",
    subject: "Subscription Activated",
    message: "Your subscription has been successfully activated.",
    sender: "subscriptions@ourplatform.com",
    recipient: "user6@example.com",
    timestamp: "2024-12-20T10:25:00Z",
  },
  {
    title: "Event Reminder",
    subject: "Upcoming Event Reminder",
    message: "Don't forget to join us for the upcoming event this weekend.",
    sender: "events@ourplatform.com",
    recipient: "user7@example.com",
    timestamp: "2024-12-20T10:30:00Z",
  },
  {
    title: "Security Alert",
    subject: "Unusual Login Attempt Detected",
    message:
      "We detected an unusual login attempt on your account. Please review.",
    sender: "security@ourplatform.com",
    recipient: "user8@example.com",
    timestamp: "2024-12-20T10:35:00Z",
  },
  {
    title: "Billing Update",
    subject: "Payment Received",
    message: "We have successfully received your payment. Thank you!",
    sender: "billing@ourplatform.com",
    recipient: "user9@example.com",
    timestamp: "2024-12-20T10:40:00Z",
  },
  {
    title: "Welcome Back",
    subject: "It's Been a While",
    message:
      "We noticed you haven't logged in for a while. Come back and see what's new!",
    sender: "no-reply@ourplatform.com",
    recipient: "user10@example.com",
    timestamp: "2024-12-20T10:45:00Z",
  },
  {
    title: "New Features",
    subject: "Check Out Our Latest Features",
    message:
      "We're excited to share the new features we've added to our platform.",
    sender: "updates@ourplatform.com",
    recipient: "user11@example.com",
    timestamp: "2024-12-20T10:50:00Z",
  },
  {
    title: "Service Downtime",
    subject: "Scheduled Maintenance",
    message:
      "Our platform will be down for scheduled maintenance on Sunday at midnight.",
    sender: "support@ourplatform.com",
    recipient: "user12@example.com",
    timestamp: "2024-12-20T10:55:00Z",
  },
  {
    title: "Account Update",
    subject: "Profile Updated Successfully",
    message: "Your account profile has been updated successfully.",
    sender: "no-reply@ourplatform.com",
    recipient: "user13@example.com",
    timestamp: "2024-12-20T11:00:00Z",
  },
  {
    title: "Referral Program",
    subject: "Invite Your Friends",
    message: "Invite your friends and earn rewards for each referral.",
    sender: "referrals@ourplatform.com",
    recipient: "user14@example.com",
    timestamp: "2024-12-20T11:05:00Z",
  },
  {
    title: "Holiday Greetings",
    subject: "Happy Holidays!",
    message: "Wishing you a wonderful holiday season and a happy new year!",
    sender: "team@ourplatform.com",
    recipient: "user15@example.com",
    timestamp: "2024-12-20T11:10:00Z",
  },
  {
    title: "Contest Alert",
    subject: "Join Our Latest Contest",
    message:
      "Participate in our contest and stand a chance to win exciting prizes.",
    sender: "contests@ourplatform.com",
    recipient: "user16@example.com",
    timestamp: "2024-12-20T11:15:00Z",
  },
  {
    title: "Product Launch",
    subject: "New Product Alert",
    message: "We're thrilled to announce the launch of our latest product.",
    sender: "products@ourplatform.com",
    recipient: "user17@example.com",
    timestamp: "2024-12-20T11:20:00Z",
  },
  {
    title: "User Survey",
    subject: "We Value Your Opinion",
    message:
      "Please take a few minutes to complete our user satisfaction survey.",
    sender: "surveys@ourplatform.com",
    recipient: "user18@example.com",
    timestamp: "2024-12-20T11:25:00Z",
  },
  {
    title: "Account Deactivation",
    subject: "Your Account Will Be Deactivated Soon",
    message:
      "We noticed you haven't used your account recently. It will be deactivated in 30 days if no activity is detected.",
    sender: "support@ourplatform.com",
    recipient: "user19@example.com",
    timestamp: "2024-12-20T11:30:00Z",
  },
  {
    title: "Support Follow-Up",
    subject: "How Can We Assist You?",
    message:
      "We're following up on your recent support request. Please let us know if you need further assistance.",
    sender: "support@ourplatform.com",
    recipient: "user20@example.com",
    timestamp: "2024-12-20T11:35:00Z",
  },
];
